#!/usr/bin/env bash
###############################################################################
# Vibe 1099 — one-shot installer.
#
#   Docker  (default): docker compose stack — postgres, redis, render, api,
#                      worker, web. Nothing on the host but Docker itself.
#   Native  (--mode native): no Docker. Installs Node 24, PostgreSQL, Redis,
#                      and the Python/WeasyPrint render service directly on the
#                      host, builds the app, and (by default) writes systemd
#                      units so the four processes start on boot.
#
# Usage — run from the repo root:
#   scripts/install.sh                     # Docker install
#   scripts/install.sh --mode native       # fully native install (needs root)
#   scripts/install.sh --mode native --no-systemd   # native, run it yourself
#
# Common flags:
#   --with-demo          seed demo data (admin@demo.firm / vibe1099-demo-password)
#   --app-url URL        public base URL (default http://localhost:8211)
#   --db-password PW     Postgres password (default: generated)
#   --master-key KEY     32-byte base64 MASTER_KEY (default: generated)
#   --no-systemd         native only: skip systemd, use scripts/native-run.sh
#   --yes                non-interactive; assume yes to prompts
#
# Idempotent-ish: re-running regenerates .env only if absent and re-applies steps.
###############################################################################
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# ---- defaults / arg parsing -------------------------------------------------
MODE="docker"
WITH_DEMO=0
USE_SYSTEMD=1
ASSUME_YES=0
APP_URL="http://localhost:8211"
DB_PASSWORD=""
MASTER_KEY=""
DB_NAME="vibe1099"
DB_USER="vibe1099"
SVC_USER="vibe1099"   # unprivileged system user for native systemd services

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode) MODE="${2:?}"; shift 2 ;;
    --mode=*) MODE="${1#*=}"; shift ;;
    --with-demo) WITH_DEMO=1; shift ;;
    --no-systemd) USE_SYSTEMD=0; shift ;;
    --yes|-y) ASSUME_YES=1; shift ;;
    --app-url) APP_URL="${2:?}"; shift 2 ;;
    --app-url=*) APP_URL="${1#*=}"; shift ;;
    --db-password) DB_PASSWORD="${2:?}"; shift 2 ;;
    --db-password=*) DB_PASSWORD="${1#*=}"; shift ;;
    --master-key) MASTER_KEY="${2:?}"; shift 2 ;;
    --master-key=*) MASTER_KEY="${1#*=}"; shift ;;
    -h|--help) sed -n '2,40p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

case "$MODE" in docker|native) ;; *) echo "error: --mode must be 'docker' or 'native'" >&2; exit 2 ;; esac

# The generated env sets NODE_ENV=production, where APP_BASE_URL / PORTAL_BASE_URL
# must be https:// unless ALLOW_HTTP_BASE_URLS=1 (packages/core/src/env.ts). A
# localhost/LAN install legitimately serves plain HTTP with no public hop, so opt
# out there; an --app-url https://… install keeps the interlock on. The flag never
# relaxes the IRS/provider endpoint checks.
case "$APP_URL" in
  https://*) ALLOW_HTTP_BASE_URLS=0 ;;
  *)         ALLOW_HTTP_BASE_URLS=1 ;;
esac

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarn:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

gen_key()      { openssl rand -base64 32; }
gen_password() { openssl rand -hex 16; }

# ---- Docker mode ------------------------------------------------------------
install_docker() {
  have docker || die "Docker not found. Install Docker Engine + Compose, or use --mode native."
  if docker compose version >/dev/null 2>&1; then DC="docker compose"
  elif have docker-compose; then DC="docker-compose"
  else die "Docker Compose not found (need 'docker compose' or 'docker-compose')."; fi

  : "${MASTER_KEY:=$(gen_key)}"
  : "${DB_PASSWORD:=$(gen_password)}"

  if [[ ! -f .env ]]; then
    log "writing .env"
    cat > .env <<EOF
# Generated by scripts/install.sh --mode docker on host $(hostname 2>/dev/null || echo host)
NODE_ENV=production
MASTER_KEY=${MASTER_KEY}
POSTGRES_PASSWORD=${DB_PASSWORD}
APP_BASE_URL=${APP_URL}
PORTAL_BASE_URL=${APP_URL}
ALLOW_HTTP_BASE_URLS=${ALLOW_HTTP_BASE_URLS}
LOG_LEVEL=info
# DATABASE_URL / REDIS_URL / RENDER_URL are set by docker-compose.yml using the
# internal service hostnames — do not set them here.
EOF
    chmod 600 .env
  else
    warn ".env already exists — leaving it untouched."
  fi

  log "building + starting the stack ($DC up -d --build)"
  $DC up -d --build

  if [[ $WITH_DEMO -eq 1 ]]; then
    log "seeding demo data"
    $DC exec -T api pnpm seed || warn "seed failed (is the api healthy yet? retry: $DC exec api pnpm seed)"
  fi

  log "done — Vibe 1099 (Docker) is starting."
  echo "   Web UI:   ${APP_URL}"
  echo "   Status:   $DC ps"
  echo "   Logs:     $DC logs -f api worker"
  [[ $WITH_DEMO -eq 1 ]] && echo "   Login:    admin@demo.firm / vibe1099-demo-password"
}

# ---- Native mode: OS package layer -----------------------------------------
PKG=""            # apt | dnf
SUDO=""
detect_os() {
  [[ "$(uname -s)" == "Linux" ]] || die "Native install supports Linux only. On macOS/other, use --mode docker."
  if [[ $EUID -ne 0 ]]; then have sudo || die "Run as root or install sudo."; SUDO="sudo"; fi
  if have apt-get; then PKG="apt"
  elif have dnf; then PKG="dnf"
  else die "No supported package manager (need apt-get or dnf). Use --mode docker."; fi
  log "detected: $(. /etc/os-release 2>/dev/null; echo "${PRETTY_NAME:-Linux}") — pkg=$PKG"
}

pkg_install() {
  if [[ $PKG == apt ]]; then $SUDO apt-get install -y --no-install-recommends "$@"
  else $SUDO dnf install -y "$@"; fi
}

install_system_deps() {
  log "installing system dependencies (Redis, Python, WeasyPrint libs, build tools)"
  if [[ $PKG == apt ]]; then
    $SUDO apt-get update
    pkg_install ca-certificates curl gnupg openssl git \
      redis-server \
      python3 python3-venv python3-pip \
      libpango-1.0-0 libpangoft2-1.0-0 libharfbuzz0b libffi-dev libjpeg62-turbo \
      libopenjp2-7 libcairo2 fonts-dejavu-core fonts-liberation
  else
    pkg_install ca-certificates curl gnupg openssl git \
      redis \
      python3 python3-pip \
      pango harfbuzz libffi libjpeg-turbo openjpeg2 cairo dejavu-sans-fonts liberation-fonts || \
      warn "some dnf package names may differ on your distro; verify WeasyPrint runtime libs."
  fi
}

ensure_node() {
  if have node && [[ "$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)" -ge 24 ]]; then
    log "Node $(node -v) already present"
  else
    log "installing Node.js 24"
    if [[ $PKG == apt ]]; then
      curl -fsSL https://deb.nodesource.com/setup_24.x | $SUDO -E bash -
      pkg_install nodejs
    else
      curl -fsSL https://rpm.nodesource.com/setup_24.x | $SUDO -E bash -
      pkg_install nodejs
    fi
  fi
  log "enabling pnpm via corepack"
  $SUDO corepack enable
  corepack prepare pnpm@9.15.9 --activate
}

install_postgres() {
  if ! have psql; then
    log "installing PostgreSQL"
    if [[ $PKG == apt ]]; then
      pkg_install postgresql postgresql-contrib
    else
      pkg_install postgresql-server postgresql-contrib
      [[ -d /var/lib/pgsql/data/base ]] || $SUDO postgresql-setup --initdb
      $SUDO systemctl enable --now postgresql
    fi
  fi
  if have systemctl; then $SUDO systemctl enable --now postgresql 2>/dev/null || true; fi

  log "creating database role '$DB_USER' and database '$DB_NAME'"
  # Create role if absent; (re)set its password to the generated one. Then create
  # the DB owned by that role. All idempotent.
  $SUDO -u postgres psql -v ON_ERROR_STOP=1 <<SQL || die "postgres provisioning failed — is the server running?"
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN;
  END IF;
END
\$\$;
ALTER ROLE ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
SELECT 'CREATE DATABASE ${DB_NAME} OWNER ${DB_USER}'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec
SQL
}

ensure_redis() {
  if have systemctl; then
    $SUDO systemctl enable --now redis-server 2>/dev/null || $SUDO systemctl enable --now redis 2>/dev/null || \
      warn "could not start redis via systemd; ensure it listens on 127.0.0.1:6379."
  fi
}

setup_render_venv() {
  log "creating render sidecar Python venv (WeasyPrint)"
  python3 -m venv "$ROOT/render/.venv"
  "$ROOT/render/.venv/bin/pip" install --upgrade pip >/dev/null
  "$ROOT/render/.venv/bin/pip" install -r "$ROOT/render/requirements.txt"
}

build_app() {
  log "installing workspace dependencies (pnpm install)"
  pnpm install --frozen-lockfile
  log "building the web SPA"
  pnpm --filter @vibe1099/web build
}

write_native_env() {
  if [[ -f .env ]]; then warn ".env already exists — leaving it untouched."; return; fi
  log "writing .env (systemd-safe: no spaces/quotes in values)"
  cat > .env <<EOF
# Generated by scripts/install.sh --mode native on host $(hostname 2>/dev/null || echo host)
NODE_ENV=production
DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/${DB_NAME}
REDIS_URL=redis://127.0.0.1:6379/3
RENDER_URL=http://127.0.0.1:8212
API_PORT=8210
MASTER_KEY=${MASTER_KEY}
APP_BASE_URL=${APP_URL}
PORTAL_BASE_URL=${APP_URL}
ALLOW_HTTP_BASE_URLS=${ALLOW_HTTP_BASE_URLS}
EMAIL_PROVIDER=auto
SMTP_FROM=no-reply@localhost
SMS_PROVIDER=none
LOG_LEVEL=info
# Native install: the only proxy hop in front of the API is scripts/serve-web.mjs.
TRUST_PROXY_HOPS=1
SESSION_INACTIVITY_MINUTES=30
SESSION_ABSOLUTE_HOURS=12
DATA_RETENTION_YEARS=4
EOF
  chmod 600 .env
}

run_migrations_seed() {
  set -a; # shellcheck disable=SC1091
  . ./.env; set +a
  log "running database migrations"
  pnpm migrate
  if [[ $WITH_DEMO -eq 1 ]]; then
    log "seeding demo data"
    pnpm seed
  fi
}

install_systemd() {
  have systemctl || { warn "systemd not available; skipping service install. Use scripts/native-run.sh."; USE_SYSTEMD=0; return; }
  local PNPM_BIN NODE_BIN
  PNPM_BIN="$(command -v pnpm)"
  NODE_BIN="$(command -v node)"

  # Unprivileged service account owning the app dir.
  if ! id "$SVC_USER" >/dev/null 2>&1; then
    log "creating service user '$SVC_USER'"
    $SUDO useradd --system --home-dir "$ROOT" --shell /usr/sbin/nologin "$SVC_USER" 2>/dev/null || \
    $SUDO useradd --system --home-dir "$ROOT" --shell /sbin/nologin "$SVC_USER" || true
  fi
  $SUDO chown -R "$SVC_USER":"$SVC_USER" "$ROOT" || warn "could not chown $ROOT to $SVC_USER"

  log "writing systemd units to /etc/systemd/system/vibe1099-*.service"
  local common="After=network.target postgresql.service redis-server.service
WorkingDirectory=${ROOT}
User=${SVC_USER}
Group=${SVC_USER}
EnvironmentFile=${ROOT}/.env
Restart=on-failure
RestartSec=3
NoNewPrivileges=true"

  $SUDO tee /etc/systemd/system/vibe1099-render.service >/dev/null <<UNIT
[Unit]
Description=Vibe 1099 render sidecar (WeasyPrint)
${common}

[Service]
WorkingDirectory=${ROOT}/render
ExecStart=${ROOT}/render/.venv/bin/gunicorn --bind 127.0.0.1:8212 --workers 2 --timeout 120 app:app

[Install]
WantedBy=multi-user.target
UNIT

  $SUDO tee /etc/systemd/system/vibe1099-api.service >/dev/null <<UNIT
[Unit]
Description=Vibe 1099 API
${common}
Wants=vibe1099-render.service

[Service]
ExecStart=${PNPM_BIN} --filter @vibe1099/api start

[Install]
WantedBy=multi-user.target
UNIT

  $SUDO tee /etc/systemd/system/vibe1099-worker.service >/dev/null <<UNIT
[Unit]
Description=Vibe 1099 worker
${common}
Wants=vibe1099-render.service

[Service]
ExecStart=${PNPM_BIN} --filter @vibe1099/worker start

[Install]
WantedBy=multi-user.target
UNIT

  $SUDO tee /etc/systemd/system/vibe1099-web.service >/dev/null <<UNIT
[Unit]
Description=Vibe 1099 web (static SPA + /api proxy)
${common}
Wants=vibe1099-api.service

[Service]
Environment=WEB_PORT=8211
Environment=API_TARGET=http://127.0.0.1:8210
ExecStart=${NODE_BIN} ${ROOT}/scripts/serve-web.mjs

[Install]
WantedBy=multi-user.target
UNIT

  $SUDO systemctl daemon-reload
  $SUDO systemctl enable --now vibe1099-render vibe1099-api vibe1099-worker vibe1099-web
}

install_native() {
  detect_os
  : "${MASTER_KEY:=$(gen_key)}"
  : "${DB_PASSWORD:=$(gen_password)}"
  install_system_deps
  ensure_node
  install_postgres
  ensure_redis
  setup_render_venv
  build_app
  write_native_env
  run_migrations_seed
  if [[ $USE_SYSTEMD -eq 1 ]]; then
    install_systemd
    log "done — Vibe 1099 (native) is running under systemd."
    echo "   Web UI:   ${APP_URL}"
    echo "   Status:   systemctl status vibe1099-api vibe1099-worker vibe1099-render vibe1099-web"
    echo "   Logs:     journalctl -u vibe1099-api -f"
  else
    log "done — start it in the foreground with:  scripts/native-run.sh"
    echo "   Web UI (once running): ${APP_URL}"
  fi
  [[ $WITH_DEMO -eq 1 ]] && echo "   Login:    admin@demo.firm / vibe1099-demo-password"
}

# ---- go ---------------------------------------------------------------------
log "Vibe 1099 installer — mode: ${MODE}"
if [[ $MODE == docker ]]; then install_docker; else install_native; fi
